### ISSUE TITLE
Night-mode switch doesn't work while grinding for 100 tredec

### ISSUE THREAD

**Issue by PeterRed4091** [prinzstani/CookieBot#25]
When I toggle the "handling of night mode" switch to "ON", the bot doesn't "prepare for night mode" as it did before the grind of baking 100 tredecillion cookies.
Bot version: 2.016 beta
Game version: 2.016 beta
The bot is also trying to get garden unlocks (currently Fern Tea) and planning to "still 18 days until next hard ascend" if those would affect the bot's strategy.
Here's my current save file in case it would be helpful: [AutomatedPeterRedBakery-NightModeInGrind.txt](https://github.com/prinzstani/CookieBot/files/2787580/AutomatedPeterRedBakery-NightModeInGrind.txt)

**Comment by prinzstani** [comment]
True, night mode one was not checked during grinding. Fixed with the beta.

**Comment by uecasm** [comment]
Unless I'm misunderstanding something, this seems like it's still an issue in 2.019.  I've set the switch to ON and I'm expecting it to (almost) immediately go to "preparing for night mode", but nothing changes; it's grinding to 1 duodecillion, waiting for christmas, waiting for garden planting, none of which seems like it should block night mode.

Also: maybe it would be better to make the switch just rotate between AUTO and OFF and have a separate button for manual START/STOP night mode independently?  Seems less confusing that way.

**Comment by prinzstani** [comment]
The current understanding is that nightmode means the bot not working at night.
That means: 
ON: the bot does not work at night.
OFF: the bot does work at night.
AUTO: the bot decides itself.

I do not see why anyone wants to put the bot into nightmode at daytime - you could just disable the bot instead by reloading the game.

**Comment by uecasm** [comment]
It still wasn't going into night mode at all though in 2.019.  Though it appears that the beta version works ok (though oddly it waits until it hits a clot cookie).  Looking at the debugger it was an issue with when it updated `AutoPlay.now` in 2.019.

Again, perhaps I'm misunderstanding something, but I thought when it prepares for night mode it switches things around to optimise for no-clicking.  Those things seem like they'd be useful to request doing manually before closing the tab or reloading without the bot, regardless of actual time.

**Comment by prinzstani** [comment]
Sure, the changes are now only working in the beta. It waits for the clot (or something similar that reduces cps) in order to buy the golden switch cheaply. The bot will buy the golden switch and the shimmering veil for the night together with some changes in the pantheon.
Night-mode optimizes for no-clicking, but not for closing the tab. This way, with night-mode on you would have the the game running anyway. So there is not really a point in switching off the bot in this case. Starting the bot just to buy the golden switch, the shimmering veil and some spirits is not a good use of it.
Still, I agree that the option "ON" is kind of silly anyway. It was included just for consistency with the other options.
